In [36]:
import pandas as pd
from sqlalchemy import create_engine

In [37]:
swiggy = pd.read_csv("Swiggy_Data_1.csv")
swiggy

,State,City,Order_Date,Restaurant_Name,Location,Category,Dish_Name,Price_INR,Rating,Rating_Count
0,Karnataka,Bengaluru,29-06-2025,Anand Sweets & Savouries,Rajarajeshwari Nagar,Snack,Butter Murukku-200gm,133.9,4.0,0
1,Karnataka,Bengaluru,03-04-2025,Srinidhi Sagar Deluxe,Kengeri,Recommended,Badam Milk,52.0,4.5,25
2,Karnataka,Bengaluru,15-01-2025,Srinidhi Sagar Deluxe,Kengeri,Recommended,Chow Chow Bath,117.0,4.7,48
3,Karnataka,Bengaluru,17-04-2025,Srinidhi Sagar Deluxe,Kengeri,Recommended,Kesari Bath,65.0,4.6,65
4,Karnataka,Bengaluru,13-03-2025,Srinidhi Sagar Deluxe,Kengeri,Recommended,Mix Raitha,130.0,4.0,0
...,...,...,...,...,...,...,...,...,...,...
197425,Sikkim,Gangtok,25-01-2025,Mama's Kitchen,Gangtok,Momos,Soya cheese chilli momo ...,112.0,4.4,0
197426,Sikkim,Gangtok,02-07-2025,Mama's Kitchen,Gangtok,Momos,Kurkure momo fried ...,140.0,4.4,0
197427,Sikkim,Gangtok,25-03-2025,Mama's Kitchen,Gangtok,Momos,Chilli cheese momo,126.0,4.4,0
197428,Sikkim,Gangtok,26-03-2025,Mama's Kitchen,Gangtok,Momos,Veg Momos (8 Pc),85.0,4.4,0
197429,Sikkim,Gangtok,27-03-2025,Mama's Kitchen,Gangtok,Momos,Soya Momo,100.0,4.4,0

In [38]:
swiggy.shape

(197430, 10)

In [39]:
swiggy.info

<bound method DataFrame.info of             State       City  Order_Date           Restaurant_Name  \
0       Karnataka  Bengaluru  29-06-2025  Anand Sweets & Savouries
1       Karnataka  Bengaluru  03-04-2025     Srinidhi Sagar Deluxe
2       Karnataka  Bengaluru  15-01-2025     Srinidhi Sagar Deluxe
3       Karnataka  Bengaluru  17-04-2025     Srinidhi Sagar Deluxe
4       Karnataka  Bengaluru  13-03-2025     Srinidhi Sagar Deluxe
...           ...        ...         ...                       ...
197425     Sikkim    Gangtok  25-01-2025            Mama's Kitchen
197426     Sikkim    Gangtok  02-07-2025            Mama's Kitchen
197427     Sikkim    Gangtok  25-03-2025            Mama's Kitchen
197428     Sikkim    Gangtok  26-03-2025            Mama's Kitchen
197429     Sikkim    Gangtok  27-03-2025            Mama's Kitchen

                    Location     Category  \
0       Rajarajeshwari Nagar        Snack
1                    Kengeri  Recommended
2                    Kengeri  Recommended
3                    Kengeri  Recommended
4                    Kengeri  Recommended
...                      ...          ...
197425               Gangtok        Momos
197426               Gangtok        Momos
197427               Gangtok        Momos
197428               Gangtok        Momos
197429               Gangtok        Momos

                                                Dish_Name  Price_INR  Rating  \
0                                    Butter Murukku-200gm      133.9     4.0
1                                              Badam Milk       52.0     4.5
2                                          Chow Chow Bath      117.0     4.7
3                                             Kesari Bath       65.0     4.6
4                                              Mix Raitha      130.0     4.0
...                                                   ...        ...     ...
197425  Soya cheese chilli momo                       ...      112.0     4.4
197426  Kurkure momo fried                            ...      140.0     4.4
197427                                Chilli cheese momo       126.0     4.4
197428                                   Veg Momos (8 Pc)       85.0     4.4
197429                                          Soya Momo      100.0     4.4

        Rating_Count
0                  0
1                 25
2                 48
3                 65
4                  0
...              ...
197425             0
197426             0
197427             0
197428             0
197429             0

[197430 rows x 10 columns]>

In [40]:
swiggy.isnull().sum()

State              0
City               0
Order_Date         0
Restaurant_Name    0
Location           0
Category           0
Dish_Name          0
Price_INR          0
Rating             0
Rating_Count       0
dtype: int64

In [41]:
swiggy.dtypes

State               object
City                object
Order_Date          object
Restaurant_Name     object
Location            object
Category            object
Dish_Name           object
Price_INR          float64
Rating             float64
Rating_Count         int64
dtype: object

In [42]:
swiggy["City"].unique()

array(['Bengaluru', 'Mumbai', 'Chennai', 'New Delhi', 'Hyderabad',
       'Kolkata', 'Ahmedabad', 'Jaipur', 'Lucknow', 'Chandigarh',
       'Indore', 'Patna', 'Bhubaneswar', 'Gurgaon', 'Kochi', 'Ranchi',
       'Guwahati', 'Raipur', 'Dehradun', 'Shimla', 'Panaji', 'Srinagar',
       'Agartala', 'Imphal', 'Shillong', 'Kohima', 'Aizawl', 'Gangtok'],
      dtype=object)

In [43]:
swiggy.columns = swiggy.columns.str.lower()

In [21]:
swiggy.head(5)

,state,city,order_date,restaurant_name,location,category,dish_name,price_inr,rating,rating_count
0,Karnataka,Bengaluru,29-06-2025,Anand Sweets & Savouries,Rajarajeshwari Nagar,Snack,Butter Murukku-200gm,133.9,4.0,0
1,Karnataka,Bengaluru,03-04-2025,Srinidhi Sagar Deluxe,Kengeri,Recommended,Badam Milk,52.0,4.5,25
2,Karnataka,Bengaluru,15-01-2025,Srinidhi Sagar Deluxe,Kengeri,Recommended,Chow Chow Bath,117.0,4.7,48
3,Karnataka,Bengaluru,17-04-2025,Srinidhi Sagar Deluxe,Kengeri,Recommended,Kesari Bath,65.0,4.6,65
4,Karnataka,Bengaluru,13-03-2025,Srinidhi Sagar Deluxe,Kengeri,Recommended,Mix Raitha,130.0,4.0,0

In [48]:
swiggy.duplicated().sum()

np.int64(27)

In [49]:
duplicates = swiggy[swiggy.duplicated()]
print(duplicates)

                 state        city order_date  \
10148        Karnataka   Bengaluru 2025-01-27
10360        Karnataka   Bengaluru 2025-08-15
10569        Karnataka   Bengaluru 2025-08-13
10753        Karnataka   Bengaluru 2025-02-27
13623        Karnataka   Bengaluru 2025-02-22
90690      West Bengal     Kolkata 2025-04-12
92018      West Bengal     Kolkata 2025-01-04
95053          Gujarat   Ahmedabad 2025-07-13
95152          Gujarat   Ahmedabad 2025-05-11
96850          Gujarat   Ahmedabad 2025-07-10
96894          Gujarat   Ahmedabad 2025-08-19
97200          Gujarat   Ahmedabad 2025-08-04
97305          Gujarat   Ahmedabad 2025-01-16
97336          Gujarat   Ahmedabad 2025-01-17
97339          Gujarat   Ahmedabad 2025-01-02
97959          Gujarat   Ahmedabad 2025-04-30
98152          Gujarat   Ahmedabad 2025-06-19
101742       Rajasthan      Jaipur 2025-07-06
110550          Punjab  Chandigarh 2025-02-06
112227          Punjab  Chandigarh 2025-03-17
112269          Punjab  Chandigarh 2025-06-11
112661          Punjab  Chandigarh 2025-04-12
112819          Punjab  Chandigarh 2025-07-24
118933  Madhya Pradesh      Indore 2025-05-18
195149         Mizoram      Aizawl 2025-04-29
195177         Mizoram      Aizawl 2025-03-08
195183         Mizoram      Aizawl 2025-02-28

                                       restaurant_name  \
10148                           The Belgian Waffle Co.
10360                                     Kanti Sweets
10569                                    Grameen Kulfi
10753                                      Chinese Wok
13623                   Olio - The Wood Fired Pizzeria
90690                    Veg Darbar by Behrouz Biryani
92018                  Sweet Truth - Cake and Desserts
95053                                              KFC
95152                                              KFC
96850                                       McDonald's
96894                                       McDonald's
97200                                   Jayhind Sweets
97305             McDonald's Gourmet Burger Collection
97336             McDonald's Gourmet Burger Collection
97339             McDonald's Gourmet Burger Collection
97959                            Veg Meals by Lunchbox
98152                  Faasos' Signature Wraps & Rolls
101742                           PINK CITY FOOD CORNER
110550                                     Burger King
112227                                             KFC
112269                                             KFC
112661                  Olio - The Wood Fired Pizzeria
112819  The Dessert Heaven - Pastry, Brownie and Cakes
118933                                    Maa Ki Rasoi
195149                                  Domino's Pizza
195177                                  Domino's Pizza
195183                                  Domino's Pizza

                      location                                     category  \
10148                  Kengeri                                  Recommended
10360                  Kengeri                                       Snacks
10569         KENGERI UPANAGAR                                  Matka Kulfi
10753   Kengeri Satellite Town                                       Drinks
13623               Whitefield                                     Desserts
90690              Thakurpukur                          Royal Curry & Thali
92018              Thakurpukur                            Cheesecake Slices
95053            Prahlad Nagar                                  Recommended
95152            Prahlad Nagar                 Hot & Crispy Chicken & Wings
96850                Ghatlodia                  McSaver Combos (2 Pc Meals)
96894                Ghatlodia     Protein Plus and Burgers with Millet Bun
97200                Ghatlodia                                      Namkeen
97305                Ghatlodia                              Burgers & Wraps
97336                Ghatlodia                                Fries & Sides
97339                Ghatlodia            Coffee & Beverages (Hot and Cold)
97959                     Sola                       Starters and Beverages
98152                     Sola                           Breakfast Specials
101742             Laxmi Vihar                                       Combos
110550               Panchkula         Korean Spicy Fest(Limited Time Only)
112227               Sector 15  Epic Value Meals for 1-2 (up to Rs 22% off)
112269               Sector 15                         Desserts & Beverages
112661               SECTOR 24                   Kids Special - Pizza Party
112819               Sector 24                                     Cupcakes
118933             Vijay Nagar                                      Chinese
195149     Only_Dominos_Aizawl                            Burgers & Parcels
195177     Only_Dominos_Aizawl                                Chicken Burst
195183     Only_Dominos_Aizawl                                Chicken Burst

                                                dish_name  price_inr  rating  \
10148                     Mini Waffle Box of 6 - Assorted     525.00     4.9
10360                                       Babycorn Puff      37.14     4.9
10569                  Desi Malai Matka Kulfi (pack Of 2)     152.54     4.9
10753                                                7 Up      57.00     4.1
13623                              Tiramisu Doughnut Cake     139.00     3.9
90690                     Royal Paneer Tikka Masala Thali     379.00     4.4
92018                                    Mango Cheesecake     209.00     4.6
95053                           Korean Tangy Chicken Roll     139.00     4.2
95152                        Hot & Crispy Chicken - 8 pcs     799.05     3.5
96850      Mc Crispy Chicken Burger + Piri Piri Fries (M)     360.00     4.0
96894     McCrispy Chicken Burger Protein Plus (2 Slices)     279.00     4.4
97200                                        Bombay Mixer      94.00     4.4
97305                               Big Spicy Paneer Wrap     241.90     5.0
97336                                 Piri Piri Spice Mix      23.80     4.7
97339                              American Mud Pie Shake     205.00     4.4
97959                                 Lemon Soda (250 mL)      49.00     4.4
98152                            Double Egg Chatpata Roll     109.00     5.0
101742                                Popcorn+ Cold Drink      99.00     4.4
110550                        Korean Spicy Chicken (7 Pc)     299.00     4.4
112227                           Classic Roll Mojito Meal     342.87     3.3
112269                  Hazelnut Iced Cappuccino reusable     209.00     4.4
112661  Kids Birthday Pizza Party with Chocolate Cake ...    3499.00     4.4
112819                             Dark Chocolate Cupcake      99.00     3.6
118933                                Honey Chilly Potato     138.00     4.4
195149                      Tandoori Loaded Paneer Parcel     139.00     4.4
195177           Southern Spice Chicken Burst Pizza (Reg)     449.00     4.4
195183                   Garlic Chicken Burst Pizza (Reg)     449.00     4.4

        rating_count
10148             11
10360             22
10569             26
10753             10
13623              1
90690              0
92018            140
95053             99
95152             79
96850              2
96894              0
97200              0
97305              4
97336              4
97339              0
97959              0
98152              1
101742             0
110550             0
112227             1
112269             0
112661             0
112819             3
118933             0
195149             0
195177             0
195183             0

In [50]:
swiggy = swiggy.drop_duplicates()

In [51]:
swiggy

,state,city,order_date,restaurant_name,location,category,dish_name,price_inr,rating,rating_count
0,Karnataka,Bengaluru,2025-06-29,Anand Sweets & Savouries,Rajarajeshwari Nagar,Snack,Butter Murukku-200gm,133.9,4.0,0
1,Karnataka,Bengaluru,2025-04-03,Srinidhi Sagar Deluxe,Kengeri,Recommended,Badam Milk,52.0,4.5,25
2,Karnataka,Bengaluru,2025-01-15,Srinidhi Sagar Deluxe,Kengeri,Recommended,Chow Chow Bath,117.0,4.7,48
3,Karnataka,Bengaluru,2025-04-17,Srinidhi Sagar Deluxe,Kengeri,Recommended,Kesari Bath,65.0,4.6,65
4,Karnataka,Bengaluru,2025-03-13,Srinidhi Sagar Deluxe,Kengeri,Recommended,Mix Raitha,130.0,4.0,0
...,...,...,...,...,...,...,...,...,...,...
197425,Sikkim,Gangtok,2025-01-25,Mama's Kitchen,Gangtok,Momos,Soya cheese chilli momo ...,112.0,4.4,0
197426,Sikkim,Gangtok,2025-07-02,Mama's Kitchen,Gangtok,Momos,Kurkure momo fried ...,140.0,4.4,0
197427,Sikkim,Gangtok,2025-03-25,Mama's Kitchen,Gangtok,Momos,Chilli cheese momo,126.0,4.4,0
197428,Sikkim,Gangtok,2025-03-26,Mama's Kitchen,Gangtok,Momos,Veg Momos (8 Pc),85.0,4.4,0
197429,Sikkim,Gangtok,2025-03-27,Mama's Kitchen,Gangtok,Momos,Soya Momo,100.0,4.4,0

## Convert the Date

In [44]:
swiggy['order_date'] = pd.to_datetime(swiggy['order_date'],format="%d-%m-%Y")

In [45]:
swiggy

,state,city,order_date,restaurant_name,location,category,dish_name,price_inr,rating,rating_count
0,Karnataka,Bengaluru,2025-06-29,Anand Sweets & Savouries,Rajarajeshwari Nagar,Snack,Butter Murukku-200gm,133.9,4.0,0
1,Karnataka,Bengaluru,2025-04-03,Srinidhi Sagar Deluxe,Kengeri,Recommended,Badam Milk,52.0,4.5,25
2,Karnataka,Bengaluru,2025-01-15,Srinidhi Sagar Deluxe,Kengeri,Recommended,Chow Chow Bath,117.0,4.7,48
3,Karnataka,Bengaluru,2025-04-17,Srinidhi Sagar Deluxe,Kengeri,Recommended,Kesari Bath,65.0,4.6,65
4,Karnataka,Bengaluru,2025-03-13,Srinidhi Sagar Deluxe,Kengeri,Recommended,Mix Raitha,130.0,4.0,0
...,...,...,...,...,...,...,...,...,...,...
197425,Sikkim,Gangtok,2025-01-25,Mama's Kitchen,Gangtok,Momos,Soya cheese chilli momo ...,112.0,4.4,0
197426,Sikkim,Gangtok,2025-07-02,Mama's Kitchen,Gangtok,Momos,Kurkure momo fried ...,140.0,4.4,0
197427,Sikkim,Gangtok,2025-03-25,Mama's Kitchen,Gangtok,Momos,Chilli cheese momo,126.0,4.4,0
197428,Sikkim,Gangtok,2025-03-26,Mama's Kitchen,Gangtok,Momos,Veg Momos (8 Pc),85.0,4.4,0
197429,Sikkim,Gangtok,2025-03-27,Mama's Kitchen,Gangtok,Momos,Soya Momo,100.0,4.4,0

## Load the Data to SQL

In [52]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "root"
password = quote_plus("Hari#K2026")
host = "127.0.0.1"
database = "swiggy_db"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}/{database}"
)

print("Connection created successfully!")

Connection created successfully!

In [53]:
swiggy.to_sql(
    name="swiggy",
    con=engine,
    if_exists="replace",
    index=False
)

197403